import { Router } from "express";
import { getHelloworldController } from "../controllers/exempleController";
import { userRegister, userSignin, userNameUpdate, getUsers, userDelete } from "../controllers/userController";
const router = Router();
router.get("/helloworld", getHelloworldController);
router.get("/users", getUsers);
router.post("/user/signup", userRegister);
router.post("/user/signin", userSignin);
router.patch("/user/:id", userNameUpdate);
router.delete("/user/:id", userDelete);
export default router;
